/**
 * Seed generator.
 *
 * Run with `tsx` (Node). It hashes the demo passwords through the SAME PBKDF2
 * code path the Worker uses, then writes worker/src/db/seed.generated.sql with
 * idempotent `INSERT OR IGNORE` statements. Apply it with:
 *   wrangler d1 execute fip-db --local  --file=./worker/src/db/seed.generated.sql
 *   wrangler d1 execute fip-db --remote --file=./worker/src/db/seed.generated.sql
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { webcrypto } from 'node:crypto';

// Ensure the Web Crypto globals exist for older Node before importing the
// shared hashing module (Node 20+ already provides globalThis.crypto).
if (!(globalThis as { crypto?: Crypto }).crypto) {
  (globalThis as { crypto?: Crypto }).crypto = webcrypto as unknown as Crypto;
}

const { hashPassword } = await import('../auth/password');
const { USERS, POLLS, LOOKS, BASE_TS } = await import('./seed.data');

function s(value: string | null): string {
  if (value === null) return 'NULL';
  return `'${value.replace(/'/g, "''")}'`;
}

async function build(): Promise<string> {
  const lines: string[] = [
    '-- GENERATED by worker/src/db/seed.ts — do not edit by hand.',
    '-- Idempotent: users use INSERT OR IGNORE (accounts preserved); poll/look',
    '-- content uses INSERT OR REPLACE so re-seeding refreshes demo imagery.',
    '',
  ];

  // Users (hash passwords through the real code path).
  for (const u of USERS) {
    const { hash, salt } = await hashPassword(u.password);
    lines.push(
      `INSERT OR IGNORE INTO users (id, username, display_name, password_hash, password_salt, bio, avatar_url, followers_count, created_at) VALUES (` +
        `${s(u.id)}, ${s(u.username)}, ${s(u.displayName)}, ${s(hash)}, ${s(salt)}, ${s(u.bio)}, ${s(u.avatarUrl)}, ${u.followers}, ${BASE_TS});`,
    );
  }
  lines.push('');

  // Polls + tags.
  POLLS.forEach((p, i) => {
    const ts = BASE_TS + i * 1000;
    lines.push(
      `INSERT OR REPLACE INTO polls (id, creator_id, option_a_image_url, option_b_image_url, option_a_votes, option_b_votes, status, created_at) VALUES (` +
        `${s(p.id)}, ${s(p.creatorId)}, ${s(p.imageA)}, ${s(p.imageB)}, ${p.votesA}, ${p.votesB}, 'active', ${ts});`,
    );
    for (const t of p.tags) {
      lines.push(
        `INSERT OR REPLACE INTO tags (id, poll_id, side, x_pct, y_pct, brand, item_name, price_cents, currency, affiliate_url) VALUES (` +
          `${s(t.id)}, ${s(p.id)}, ${s(t.side)}, ${t.x}, ${t.y}, ${s(t.brand)}, ${s(t.item)}, ${t.priceCents}, ${s(t.currency ?? 'USD')}, ${s(t.url)});`,
      );
    }
  });
  lines.push('');

  // Looks + items.
  LOOKS.forEach((l, i) => {
    const ts = BASE_TS + i * 1000;
    lines.push(
      `INSERT OR REPLACE INTO looks (id, user_id, image_url, caption, published_at) VALUES (` +
        `${s(l.id)}, ${s(l.userId)}, ${s(l.image)}, ${s(l.caption)}, ${ts});`,
    );
    for (const it of l.items) {
      lines.push(
        `INSERT OR REPLACE INTO look_items (id, look_id, x_pct, y_pct, brand, item_name, price_cents, currency, affiliate_url) VALUES (` +
          `${s(it.id)}, ${s(l.id)}, ${it.x}, ${it.y}, ${s(it.brand)}, ${s(it.item)}, ${it.priceCents}, ${s(it.currency ?? 'USD')}, ${s(it.url)});`,
      );
    }
  });
  lines.push('');

  return lines.join('\n');
}

const sql = await build();
const outPath = fileURLToPath(new URL('./seed.generated.sql', import.meta.url));
writeFileSync(outPath, sql, 'utf8');
console.log(`Seed SQL written to ${outPath}`);
console.log(`Users: ${USERS.length} | Polls: ${POLLS.length} | Looks: ${LOOKS.length}`);
